////////////////////////////////////////////////////////////////////////////////
//                                                                            // 
//                                WARNING!                                    //
//                                                                            // 
//    This file is automatically generated during the configuration stage     // 
//    of the installation.  To edit it, change the template files in          // 
//    install/templates and rerun the configuration.                          // 
//                                                                            // 
////////////////////////////////////////////////////////////////////////////////

#include "direct_interface.hpp"
#include "kernels.hpp"
#include "energy.hpp"

namespace latticeQBP {
  template class LatticeFlowDirectInterface<LatticeEnergyMinimizer<2, Full2d_4> >;

template class LatticeFlowDirectInterface<LatticeEnergyAdjuster<2, Full2d_4> >;

}
